name: Build and Attach Binary to Release

on:
  release:
    types:
      - published

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile garmin-convert-weight.py
      # Save the binary in a variable for reuse
      env:
        BINARY_PATH: dist/garmin-convert-weight

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: garmin-convert-weight
        path: dist/garmin-convert-weight

    - name: Attach binary to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/garmin-convert-weight
        asset_name: garmin-convert-weight
        asset_content_type: application/octet-stream
